name: Deploy to Production
run-name: Move It, Move It! 
on:
  push:
    branches:
      - main
      
jobs:
  Deploy-to-Prod:
    name: Called Workflow
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
